FROM eric_centos:v4
# RUN source /etc/profile
# RUN mkdir -p /usr/app/PerformanceScore/
# VOLUME ["/usr/runningapp"]
RUN mkdir -p /usr/runningapp
COPY . /usr/runningapp
# COPY . /usr/app/PerformanceScore/
# WORKDIR /usr/app/PerformanceScore/
# CMD npm start
# CMD ["pm2", "start", "./bin/www", "--no-daemon"]
# RUN ["pm2","start","./bin/www","--no-daemon"]


# # CMD ["pm2","start ./bin/www --name PerformanceScore"]
# # RUN pm2 start ./bin/www --name PerformanceScore

# RUN npm install -g pm2
# RUN pm2 dump
# # dump will start pm2 daemon and create everything needed

# VOLUME ["/usr/app/PerformanceScore/"]
# # don't put the files in docker container, user -v

# CMD ["pm2", "start", "./bin/www", "--no-daemon"]
ENV NODE_ENV production
EXPOSE 3030

WORKDIR /usr/runningapp/

# CMD ["pm2", "start", "--auto-exit", "--env", "ITE", "process.yml"]


# ######### Build with pm2 ###########
# FROM node:7.8.0

# RUN npm install pm2 -g

# VOLUME ["/usr/app"]

# # Expose ports
# EXPOSE 3030

# WORKDIR /usr/app

# # Start process.yml
# CMD ["pm2-docker", "start", "--auto-exit", "--env", "ITE", "process.yml"]