var API_HOST = {
    development: "http://10.142.214.87:8999/",
    ITE: "http://10.142.214.87:8999/",
    production:"http://10.138.4.208:8999/"
}[process.env.NODE_ENV || 'development']

var config = { 
    "SYS" :{
        "AES":{
            "KEY_256": 'FLKC7B6BPMR6GZBCGRXGECE3WGNBPPFB', //32字元 256bit
            "KEY_128": 'T8MY8Z3NMDFLCMH3', //16字元 128bit   
            "IV": '47B42PARBBWHLGM7'  //16字元 128bit            
        }
    },
    "CIVET":{
        "APPID":"OJPAbtKShN01",
        "ACCOUNT":"pdsshr",
        "PWD":'Foxconn99',
        "HOST":"http://civetInterface.foxconn.com/",
        "URL":{
            "GET_ACCESS_TOKEN":"open/access_token",
            "GET_USERINFO":"open/get_user_info",
            "GET_QRCODE":"Open/ScanPage?redirect_uri=http://10.142.214.89:3030/civetsso&scope=snsapi_userinfo&NonBorder=true&NonNav=true",
            "GET_SCANRESLUT":"Open/ScanResult",
            "POST_SENDMSG":"open/sendMsg",
        }
    },    
    "API": {  
        "host": API_HOST,  
        // "host": "http://10.142.214.102:8999/",  
        "url":{
            "sys":{
                "menu":"sys/menu"
            },
            "login":{
                "loginAccount":"sys/account/login",
                "checkAccount":"sys/account/check",
                "civetLoginAccount":"sys/account/sso/login"
            },
            "logout":{
                "logoutAccount":"sys/account/logout",
            },
            "account":{
                "getList":"account",
                "getEditList":"account",
                "getEditTableList":"account",
                "updateRow":"account",
                "updateHeadBodyData":"sys/account",
                "resetPassword":"sys/account/reset_by_admin",
                "saveData":"account",
                "saveHeadBodyData":"sys/account",
                "deleteRow":"account",
                "resetPasswordByUser":"sys/account/reset_by_user",
                "checkAccountExist":"/sys/account/check_account?account="
            },
            "options":{
                "getList":"option",
                "getEditList":"option",
                "getEditTableList":"option",
                "updateHeadBodyData":"option",
                "saveHeadBodyData":"option",
				"deleteRow":"option",
                "getByKey":"option/search/findByKey?key="
            },            
            "privilege":{
                "getList":"privilege",
                "getEditList":"privilege",
                "updateRow":"privilege",
                "saveData":"privilege",
                "deleteRow":"privilege"
            },
            "role":{
                "getList":"role",
                "getEditList":"role",
                "getEditTableList":"role",
                "updateHeadBodyData":"sys/role",
                "saveHeadBodyData":"role",
				"deleteRow":"role"
            },
            "log":{
                "getList":"log/search/filter",
                "getEditList":"log",
                "updateRow":"log",
                "saveData":"log"
            },
            "pagemanger":{
                "getList":"page",
                "getEditList":"page",
                "getEditTableList":"page",
                "updateHeadBodyData":"page",
                "saveHeadBodyData":"page",
				"deleteRow":"page"
            },            
            "member":{
                "getList":"member",
                "getEditList":"member",
                "getEditTableList":"member",
                "getTeamIdByLeader":"member/search",
                "updateRow":"member",
                "saveData":"member",
                "saveHeadBodyData":"member",
                "updateHeadBodyData":"member",
                "getSimpleList":"member/search/findTeamSimpleInfoAll",
                "getTeamAverage":"team/member/average",
                "getManagerConfirmMemberList":"team/members",
            },
            "monthscore":{
                "getList":"month_score",
                "getEditList":"month_score",
                "getMonthScoreNewVersion":"team/month_score/new_version",
                "getMonthScoreNewVersionByAccount":"team/month_score/new_version_by_account",
                "getSearchList":"month_score/search",
                "updateRow":"month_score",
                "saveData":"month_score",
                "saveBodyData":"team/month_score",
                "submitBodyData":"team/month_score/leader_submit",
                "accessLog":"month_score_access_log",
                "findScoreSummary":"team/month_score/find_score_summary",
                "managerConfirm":"team/month_score/manager_confirm",
                "alert":"team/month_score/alert",
                "exportExcel":"summary_excel",
                "getTeamLeaderList":"team/month_score/find_no_submit_team_leader",
                "managerReject":"team/month_score/manager_reject"
            },
            "monthscorelist":{
                "getList":"month_score",
                "getEditList":"month_score",
                "getScoreList":"team/month_score/find_score_info",
                "getScoreListByAccount":"team/month_score/find_score_info_by_account",
                "updateRow":"month_score",
                "saveData":"month_score"
            },
            "monthscoreqa":{
                "getList":"month_score_qa",
                "getEditList":"month_score_qa",
                "updateRow":"month_score_qa",
                "saveData":"month_score_qa"
            },
            "weighting":{
                "getList":"team/weighting?year=",
                "getEditList":"team_weighting",
                "updateRow":"team_weighting",
                "saveData":"team_weighting",
                "getListByYear":"team_weighting",
                "getListByYearAndTeamId":"team_weighting"
            },
            "project":{
                "getList":"project_info",
                "getEditList":"project_info",
                "getEditTableList":"project_info",
                "updateHeadBodyData":"project_info",
                "saveHeadBodyData":"project_info",
                "deleteRow":"project_info",
                "getByStartYear":"project_info/search/findByYear?startYear=",
                "closeById":"project/project_info/close"
            },
            "projectscore":{
                "getById":"project_info",
                "giveScore":"project/project_info/givescore"
            },
            "rankpercent":{
                "getByYear":"year/rank_percent?year="
            },
            "report":{
                "getListData":"year/result",
                "getChartData":"year/result"
            },
            "civet":{
                "getQrcode":"civet/qrcode",
                "scan":"civet/scan"
            },
            "yearsettlement":{
                "getList":"year/settlements",
                "getEditList":"year/settlement",
                "saveData":"year/settlement/modify_rank"
            },
        }
    }
};

module.exports = config;